#!/bin/bash
echo -e "Enter the nameof file : \C"
read file_name
if  [ -f $file_name ]
then
    if [ -w $file_name ]
    then
        echo "Type some texts.  To quit press ctrl+d"
        cat >> $file_name
    else
        echo "File don't have write permission"
    fi
else
   echo "$file_name not exist."
 fi

