#!/bin/bash
num1=20
num2=5
echo $(( num1 + num2 ))
echo $(( num1 - num2 ))
echo $(( num1 * num2 ))
echo $(( num1 / num2 ))
echo $(( num1 % num2 ))

#OR 
echo $(expr $num1 + $num2 )
echo $(expr $num1 - $num2 )
echo $(expr $num1 \* $num2 )
echo $(expr $num1 / $num2 )
echo $(expr $num1 % $num2 )

num3=20.5
num4=6
num5=27
#doing floating point Arithmatic
echo "$num3+$num4" | bc #here bc is used to perfrom floating point Arithmatic operation
echo "$num3-$num4" | bc
echo "$num3*$num4" | bc
echo "scale=2;$num3/$num4" | bc  #scale=2; used here to print upto 2 decimal place
echo "$num3%$num4" | bc
echo "scale=2; sqrt($num5)" | bc -l  #here -l is used to include maths library
